config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to @task
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit</h1>

<%= form_for @task do |f| %>
    <%= f.text_field :title %>
    <%= f.text_field :details %>
    <%= f.check_box :completed %>

    <%= f.submit "submit" %>
<% end %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<ul>
<% @tasks.each do |task| %>

<li> <%= link_to task.title, task_path(task) %> - <%= task.completed %> <%= link_to "DELETE", task_path(task), method: :delete %></li>

<% end %>

</ul>

<%= link_to "ADD TASK", tasks_new_path %>

app/views/tasks/new.html.erb
<h1>New</h1>

<%= form_for @task do |f| %>
    <%= f.text_field :title %>
    <%= f.text_field :details %>

    <%= f.submit "submit" %>
<% end %>

app/views/tasks/show.html.erb
<h1>Task</h1>

<%= @task.title %>
<%= @task.details %>
<%= @task.completed %>


<%= link_to "EDIT TASK", edit_task_path(@task) %>
<%= link_to "SEE ALL TASKS", tasks_path %>